apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - akka-cluster-visualizer-auth.yaml
spec:
  serviceAccountName: akka-cluster-visualizer
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
patchesStrategicMerge:
  - podinfo-values.yaml
  - akka-cluster-visualizer-values.yaml
