---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 1m0s
  ref:
    branch: dev-team
  secretRef:
    name: dev-team-auth
  url: https://github.com/au2001/flux2-multi-tenancy

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team
  namespace: apps
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: dev-team
  sourceRef:
    kind: GitRepository
    name: dev-team

